GlowingPixels/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gallery.urls', namespace='gallery')),
    path('accounts/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/urls.py
"""Urls patterns of the Gallery App"""
from . import views
from django.urls import path

app_name = 'gallery'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('add/image', views.create_image , name='addImage'),
    path('<str:category>/', views.category_images, name='category'),
    path('like/<int:id>/', views.add_likes, name="like"), #hardcoded urlpattern implemented html id
    path("like/<int:id>/check/", views.has_liked, name="check_like") #exclusively for ajax check of user liked images
]

users/urls.py
from django.urls import path
from . import views
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required

app_name = "users"

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('settings/', login_required(views.settings), name='settings'),
	path('profile/', login_required(views.profile), name='profile'),
    path("user/<str:fellow_username>/", views.fellow_user, name="fellow_user"),
    path("search/", views.search_user, name="search_user"),
]

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <link rel="icon" href="{% static "images/icon.png" %}" type="image/x-icon">
        <!-- CDN for font Awaesome -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" 
        integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" 
        crossorigin="anonymous">
        <!-- CDN for google font -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Cabin" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Exo" rel="stylesheet">
        <!-- link for homepage css -->
        <link rel="stylesheet" href="{% static 'css/base_homepage.css' %}">
    </head>
    <body>
        <!-- navbar for the homepage -->
        <div class="homepage_navbar">
            <div class="burger_icon">
                <i class="fas fa-bars"></i>
            </div>
            <div class="brand_name">
                <a href="{% url 'gallery:homepage' %}">glowingpixels</a>
            </div>
            <div class="nav_content">

                {% if user.is_authenticated %}
                    <a href="{% url 'users:profile' %}" class="side_line">
                        {{ user.first_name }}
                    </a>
                    <a href="{% url 'logout' %}">
                        <span>Logout</span>
                    </a>
                {% else %}
                    <a href="{% url 'login' %}" class="side_line">
                        <span>Login</span>
                    </a>
                    <a href="{% url 'users:signup' %}">
                        <span>Sign Up</span>
                    </a>
                {% endif %}

            </div>
        </div>

        <!-- side bar that contains category -->
        <div class="category_side">
            <div class="category">
                <span class="menu_heading">Image Categories</span>
                <ul class="category_list">
                {% for category in categories %}
                    <li class="list_items"><span>{{ category }}</span>
                        {% for sub in category.subcategory_list.all %}
                        <ul class="sub_category">
                            <li><a href="">{{sub}}</a></li>
                        </ul> 
                        {% endfor %}
                    </li>            
                {% endfor %}
                </ul>
            </div>
        </div>
        <div class="screen_side"></div>
        

    {% block content %}

        <!-- awaesome content goes here (awaesome because its written by me) -->

    {% endblock %}

    <!-- footer -->
    {% include "base/footer.html" %}

    <!-- links for the script tag -->
    {% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- js file link -->
    <script src="{% static 'js/base_homepage.js' %}"></script>
    {% endblock %}
    </body>
</html>

templates/base/base_homepage.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <title>Glowing Pixels</title>
        <link rel="icon" href="{% static "images/icon.png" %}" type="image/x-icon">
        <!-- -----------------------CDN for font Awaesome------------------------------------ -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" 
        integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" 
        crossorigin="anonymous">
        <!-- ------------------------CDN for google font------------------------------------- -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Cabin" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Exo" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Kreon" rel="stylesheet">
        <!-- -----------------homepage CDNs of google-fonts---------------------------------- -->
        <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
        <!-- --------------------link for homepage css--------------------------------------- -->
        <link rel="stylesheet" href="{% static 'css/base_homepage.css' %}">
    </head>
    <body>
        <!-- --------------------navbar for the homepage------------------------------------- -->
        <div class="homepage_navbar">
            <div class="burger_icon">
                <i class="fas fa-bars"></i>
            </div>
            <div class="brand_name">
                <a href="{% url 'gallery:homepage' %}">glowingpixels</a>
            </div>
            <div class="nav_content">

                {% if user.is_authenticated %}
                   
                    <a href="{% url 'users:profile' %}" class="user_details hide">
                        <div class="profile_image">
                            <img src="../../static/images/p1.jpg" alt="image">
                        </div>
                        <span  class="user_name"> {{ user.first_name }}</span>
                    </a>
                    <a href="#" class="cart_icon">
                        <i class="fas fa-shopping-cart" style="font-size:120%"></i>
                    </a>

                    <a href="{% url 'logout' %}"  class="side_line">
                        <span>Logout</span>
                    </a>
                {% else %}
                    <a href="{% url 'login' %}">
                        <span>Login</span>
                    </a>
                    <a href="{% url 'users:signup' %}"  class="side_line">
                        <span>Sign Up</span>
                    </a>
                {% endif %}

            </div>
        </div>

        <!-- ----------------------side bar that contains category------------------------- -->
        <div class="category_side">
            <div class="user_info">
                {% if user.is_authenticated %}

                <span>
                    <a href="{% url 'users:profile' %}" class="user_details">
                        <div class="profile_image">
                            <img src="../../static/images/p1.jpg" alt="image">
                        </div>
                        <span  class="user_name"> {{ user.first_name }}</span>
                    </a>
                    <a href="{% url 'logout' %}">
                        <span>Logout</span>
                    </a>
                </span>

                {% else %}

                
                <span>
                    <i class="fas fa-user-tie"></i>
                    <a href="{% url 'login' %}">
                        <span>Login</span>
                    </a>
                    <a href="{% url 'users:signup' %}">
                        <span>Sign Up</span>
                    </a>
                </span>

                {% endif %}
            </div>

            <div class="category">
                <span class="menu_heading">Image Categories</span>
                <ul class="category_list">
                {% for category in categories %}
                    <li class="list_items"><span>{{ category }}</span>
                        {% for sub in category.subcategory_list.all %}
                        <ul class="sub_category">
                            <li><a href="">{{sub}}</a></li>
                        </ul> 
                        {% endfor %}
                    </li>         
                {% endfor %}
                </ul>
            </div>
        </div>
        <div class="screen_side"></div>
        

    {% block content %}

        <!-- -------awaesome content goes here (awaesome because its written by me)------ -->

    {% endblock %}

    <!-- ----------------------------------footer----------------------------------------- -->
    {% include "base/footer.html" %}

    <!-------------------------- links for the script tag--------------------------------- -->
    {% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- ---------------------------js file link------------------------------------------ -->
    <script src="{% static 'js/base_homepage.js' %}"></script>
    {% endblock %}
    </body>
</html>

templates/base/footer.html
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'css/footer.css' %}">
<footer class="footer_container">
        <div class="details_sections_row">
            <div class="details_sections_col">
                <h3>PROJECT</h3>
                <ul>
                    <li><a href="#"><i class="fas fa-bong footer_icon_color_1"></i>blah</a></li>
                    <li><a href="#"><i class="fas fa-bong footer_icon_color_1"></i>blah</a></li>
                    <li><a href="#"><i class="fas fa-bong footer_icon_color_1"></i>blah</a></li>
                    <li><a href="#"><i class="fas fa-bong footer_icon_color_1"></i>blah</a></li>
                </ul>
            </div>
            <div class="details_sections_col">
                <h3>PROJECT</h3>
                <ul>
                    <li><a href="#"><i class="fas fa-bong footer_icon_color_2"></i>blah</a></li>
                    <li><a href="#"><i class="fas fa-bong footer_icon_color_2"></i>blah</a></li>
                    <li><a href="#"><i class="fas fa-bong footer_icon_color_2"></i>blah</a></li>
                </ul>
            </div>
            <div class="details_sections_col">
                <h3>SUPPORT</h3>
                <ul>
                    <li><a href="#"><i class="fas fa-bong footer_icon_color_3"></i>blah</a></li>
                    <li><a href="#"><i class="fas fa-bong footer_icon_color_3"></i>blah</a></li>
                    <li><a href="#"><i class="fas fa-bong footer_icon_color_3"></i>blah</a></li>
                </ul>
            </div>
            <div class="details_sections_col">
                <h3>COMPANY</h3>
                <ul>
                    <li><a href="#"><i class="fas fa-bong footer_icon_color_4"></i>blah</a></li>
                    <li><a href="#"><i class="fas fa-bong footer_icon_color_4"></i>blah</a></li>
                    <li><a href="#"><i class="fas fa-bong footer_icon_color_4"></i>blah</a></li>
                </ul>
            </div>
        </div>
        <div class="bottom_formalities">
            <span class="littel_love">
                Clicked with 
                <i class="fas fa-heart"></i>
                and
                <i class="fas fa-camera-retro"></i>
            </span>
            <span class="copy_right">
                {% now "Y" %}
                <i class="far fa-copyright" style="font-size:90%"></i>
                glowingpixels.in
            </span>
        </div>
        
    </footer>