GlowingPixels/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gallery.urls', namespace='gallery')),
    path('accounts/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/urls.py
"""Urls patterns of the Gallery App"""
from . import views
from django.urls import path

app_name = 'gallery'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('add/image', views.create_image , name='addImage'),
    path('<str:category>/', views.category_images, name='category'),
    path('like/<int:id>/', views.add_likes, name="like"), #hardcoded urlpattern implemented html id
    path("like/<int:id>/check/", views.has_liked, name="check_like") #exclusively for ajax check of user liked images
]

users/urls.py
from django.urls import path
from . import views
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required

app_name = "users"

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('settings/', login_required(views.settings), name='settings'),
	path('profile/', login_required(views.profile), name='profile'),
    path("user/<str:fellow_username>/", views.fellow_user, name="fellow_user"),
    path("search/", views.search_user, name="search_user"),
]

gallery/models.py
"""
A very basic Gallery App Model that has an image and its description with date
"""
from django.contrib.auth import get_user_model
from django.template.defaultfilters import slugify
from datetime import datetime
from django.db import models
from stdimage import StdImageField
from django.conf import settings
from .compress import compress

User = get_user_model()

class ImageCategory(models.Model):
    """Category class to categorize the images"""

    category = models.CharField(max_length=100)
    representative_image = StdImageField(upload_to='category_images/', variations={'thumbnail': (786, 1048, True)}, blank=True)

    class Meta:

        verbose_name = "Image Category"
        verbose_name_plural = "Image Categories"

    def save(self, *args, **kwargs):
        representative_image = compress(self.representative_image)
        self.representative_image = representative_image
        super().save(*args, **kwargs)

    def __str__(self):
        return str(self.category)

class SubCategory(models.Model):

    parent =  models.ForeignKey(ImageCategory, on_delete=models.CASCADE, related_name='subcategory_list')
    name = models.CharField(max_length=100)

    class Meta:

        verbose_name = "Sub-Category"
        verbose_name_plural = "Sub-Categories"
    
    def __str__(self):
        return str(self.name)

class Tag(models.Model):
    """
    A collection of all tags of an image
    """
    name = models.CharField(max_length=25)

    class Meta:
    
        verbose_name = "Tag"
        verbose_name_plural = "Tags"

    def __str__(self):
        return str(self.name)


class Image(models.Model):
    """ 
    Main Class of Gallery
    """
    slug = models.SlugField(max_length=50, unique=True, blank=True, help_text="THIS is field is AUTO-GENERATED keep it empty")
    category = models.ForeignKey(ImageCategory, on_delete=models.SET_DEFAULT, default=0)
    contributor = models.ForeignKey(User, on_delete=models.CASCADE)
    image = StdImageField(upload_to='images/', variations={'thumbnail': (786, 1048, True)}, blank=True)
    label = models.CharField(max_length=100, help_text="Name of the image must be related to image attributes")
    tags = models.ManyToManyField(Tag, blank=True, related_name='images')
    date = models.DateField(auto_now=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='pic_liked')
   
    class Meta:

        verbose_name = "Image"
        verbose_name_plural = "Images"


    def save(self, *args, **kwargs):
        self.slug = slugify(self.label)
        super(Image, self).save(*args, **kwargs)    

    def __str__(self):
        return "Image: " + str(self.category)

gallery/forms.py
from django.forms import ModelForm
from .models import Image

class  ImageCreateForm(ModelForm):

    class Meta:
        model = Image
        exclude = ['contributor', ]

gallery/views.py
"""A basic view for the Gallery App"""
from django.db.models import Count
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.views import View

from .models import Image, ImageCategory
from .forms import ImageCreateForm

def homepage(req):
    """
    Default view that renders all category
    """
    images = ImageCategory.objects.all()
    context = {
            'images': images,
       }
    return render(req, 'gallery/homepage.html', context=context)

def category_images(req, category):
    category_obj = ImageCategory.objects.filter(category=category)
    images = Image.objects.annotate(like_count=Count('likes')).order_by('-like_count').filter(category__in=category_obj)[:24]
    context = {
            'images': images,
            'category': category,
        }
    return render(req, 'gallery/category.html', context=context) 
    
@login_required
def create_image(request):
    if request.method == 'POST':
        form = ImageCreateForm(request.POST, request.FILES)
        
        if form.is_valid():
            instance = form.save(commit=False)
            instance.contributor = request.user
            instance.save()
            return redirect('gallery:homepage')
    else:
        form = ImageCreateForm()
        return render(request, 'gallery/imagecreate.html', {'form': form})

@login_required
def add_likes(request, id):
    
    user = request.user
    image = Image.objects.get(id=id)
    if user.pic_liked.filter(id=image.id).exists():
        image.likes.remove(user)
        image.save()
        return HttpResponse("Unliked")
    else:
        image.likes.add(user)
        image.save()
        return HttpResponse("Liked")

@login_required
def has_liked(request, id):

    user = request.user
    image = Image.objects.get(id=id)
    if user.pic_liked.filter(id=image.id).exists():
        return HttpResponse("True")
    else:
        return HttpResponse("False")

templates/gallery/category.html
{% extends "base/base_homepage.html" %}
{% load staticfiles  %}

<title>
{% block title %}
    Glowing Pixels| {{ category }}
{% endblock %}
</title>

{% block content %}

{% endblock %}

templates/gallery/homepage.html
{% extends "base/base_homepage.html" %}
{% load staticfiles  %}

<title>
{% block title %}
    Glowing Pixels
{% endblock %}
</title>

{% block content %}
    <!-- ------------------------------css link---------------------------------------- -->
    <link href="{% static 'css/homepage.css' %}" rel="stylesheet">

    <!-- ---------------------------search container------------------------------------ -->
    <div class="search_home_container">
        <div class="intro_text">
            <div class="text_line_1">BEST QUALITY IMAGES</div>
            <div class="text_line_2">WITH</div>
            <div class="text_line_3">LOWEST PRICE EVER</div>
        </div>
        <div class="search_bar">
            <input type="text" placeholder="">
            <button type="button">Search</button>
            <div class="search_result">
                <a href="#">
                    <span>blah</span>
                </a>
                <a href="#">
                    <span>blah</span>
                </a>
                <a href="#">
                    <span>blah</span>
                </a>
                <a href="#">
                    <span>blah</span>
                </a>
                <a href="#">
                    <span>blah</span>
                </a>
            </div>

        </div>
        
    </div>

    <!-- ----------------------------img categories block---------------------------------- -->
    <div class="category_block_row">
        {% for image in images %}
        <div class="category_block_col">
        <a href="{% url 'gallery:category' image.category %}">
            <img src="{{ image.representative_image.thumbnail.url }}" alt="image">
            <div class="category_name">
                {{ image.category }}
            </div>
        </a>
        </div>
        {% endfor %}

    </div>

{% endblock %}
    
{% block scripts %}
{{ block.super }}
    <script src="{% static 'js/homepage.js' %}"></script>
{% endblock %}

templates/gallery/homepage_old.html
{% extends "base/base.html" %}
{% load staticfiles  %}

<title>
{% block title %}
    Glowing Pixels
{% endblock %}
</title>

{% block content %}
    <link href="{% static "css/homepage.css" %}" rel="stylesheet">
    {% if category %}
        <p> Category : {{ category }} </p>
    {% endif %}
        <div class="bag">
            <div class="row-u">
            
            {% for img in images %}
                <!-- img cards -->
                <div class="col-u">
                    {% if img.image %}
                    <img class="imgThumbnails" src="{{ img.image.thumbnail.url }}" alt="Images"  src_full="{{ img.image.url }}">
                    <div class="albumName">
                        <a href="{% url 'gallery:gallery' img.category %}">
                            <span class="onThumbnail">
                                {{ img.category }}
                            </span>
                        </a>
                    </div>
                    
                    <div class="enlarge">
                        <div class="backLay onThumbnail">
                            <i class="fas fa-expand"></i>
                        </div>
                    </div>

                    <div class="postBy">
                        <a href="{% url 'users:fellow_user' img.contributor %}">
                            <span class="onThumbnail">
                                By {{ img.contributor }}
                            </span>
                        </a>
                    </div>

                    <div class="publishedOn">
                        <span class="onThumbnail">Published on {{ img.date }}</span>
                    </div>
                    
                    <div class="lovedBtn" id="/like/{{ img.id }}/" likes="{{ img.likes.count }}"><!--The ID of the Love button acts as an urlpattern for the ajax call-->
                        <a style="text-decoration:none"><i class="fas fa-heart"></i></a>
                    </div>
                   {% endif %}

                </div>
                {% endfor %}

            </div>
        </div>

        <!-- stuff after onClick zoom -->
        <div class="overlay"></div>
        <div class="zoomImg">
            <img src="#" alt="image" class="imgProperty">
            <div class="afterZoomDetails">
                <a href="#" class="postByName"></a>
                <div class="totalLike">
                    <i class="fas fa-heart"></i>
                    <span></span> <!--To render Likes count-->
                </div>
                <div class="download">
                    DOWNLOAD<!--TODO: implement the Functionality-->
                    <i class="fas fa-cloud-download-alt"></i>
                </div>
            </div>
        </div>

    {% endblock %}
    
   {% block scripts %}
    {{ block.super }}
        <script src="{% static 'js/homepage.js' %}"></script>
    {% endblock %}

templates/gallery/image_cards.html
{% for img in images %}
<!-- img cards -->
<!--Homepage.js and Homepage.css is required for proper functioning-->
<div class="col-u">
    {% if img.image %}
    <img class="imgThumbnails" src="{{ img.image.thumbnail.url }}" alt="Images"  src_full="{{ img.image.url }}">
    <div class="albumName">
        <a href="{% url 'gallery:gallery' img.tag %}">
            <span class="onThumbnail">
                {{ img.tag }}
            </span>
        </a>
    </div>
    
    <div class="enlarge">
        <div class="backLay onThumbnail" likes="{{ img.likes.count }}">
            <i class="fas fa-expand"></i>
        </div>
    </div>

    <div class="postBy">
        <a href="{% url 'users:fellow_user' img.contributor %}">
            <span class="onThumbnail">
                By {{ img.contributor }}
            </span>
        </a>
    </div>

    <div class="publishedOn">
        <span class="onThumbnail">Published on {{ img.date }}</span>
    </div>
    
        <div class="lovedBtn" id="/like/{{ img.id }}/"><!--The ID of the Love button acts as an urlpattern for the ajax call-->
        <a style="text-decoration:none"><i class="fas fa-heart"></i></a>
    </div>
    {% endif %}

</div>
{% endfor %}

templates/gallery/imagecreate.html
{% extends "base/base.html" %}
{% load staticfiles %}

{% block title %}
    Sign Up|Glowing Pixels
{% endblock %}

{% block content %}
{% load widget_tweaks %}

    <!--I have explicitly used Signup page's css but you may change based upon your preferences-->
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">

    <!--form-->
    <div class="container">
                <div class="formbody">

                    <p style="font-size: 50px">Submit Your ART</p>
                    <form enctype="multipart/form-data" method="POST">
                        {% csrf_token %}

                        <div class="row">
                            
                                {% render_field form.tag class="form-control" placeholder="Category" %}
                                                      
                        
                                {% render_field form.label class="form-control" placeholder="Name your Art" %}
                        
                        </div>


                        <div class="row">
                            
                                {% render_field form.descriptions class="form-control" placeholder="A vivid art description" %}
                            
                        </div>

             

                               
                            <div style="display:none">
                                <button type="button" class="btn btn-outline-secondary" data-toggle="tooltip" title="Your Masterpiece">Upload</button>
                            </div>
                            <div class="custom-file">
                                {% render_field form.image class="custom-file-label" id="inputGroupFile03" %}
                                <label class="custom-file-label" for="inputGroupFile03"></label>
                            </div>
                        
                                            
                        <div class="d1">
                            <input type="submit" class="btn btn-primary" value="Publish">
                        </div>

                    </form>

                </div>
    </div>
{% endblock %}